<?xml version = "1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name= "explorer_bot">

<xacro:property name = "chassis_length" value = "0.6"/>
<xacro:property name = "chassis_width" value = "0.8"/>
<xacro:property name = "chassis_height" value = "0.3"/>

<xacro:property name = "wheel_radius" value = "0.12"/>
<xacro:property name = "wheel_width" value = "0.06"/>
<xacro:property name = "wheel_offset" value = "-0.07"/>

<xacro:property name = "material_density" value = "2650.0"/>
<xacro:property name = "pi" value = "3.14159"/>

<xacro:property name = "chassis_mass" value = "${material_density*chassis_length*chassis_width*chassis_height}"/>
<xacro:property name = "wheel_mass" value = "${material_density*pi*wheel_radius*wheel_radius*wheel_width}"/>

<xacro:property name = "wheel_iz" value = "${0.5*wheel_mass*wheel_radius*wheel_radius}"/>
<xacro:property name = "wheel_ixy" value = "${(1/12)*wheel_mass*(3*wheel_radius*wheel_radius+wheel_width*wheel_width)}"/>

<xacro:macro name = "wheel_inertia">
<inertial>
<origin rpy = "0 0 0" xyz = "0 0 0"/>
<mass value = "${wheel_mass}"/>
<inertia ixx = "${wheel_ixy}" ixy = "0" ixz = "0" iyy = "${wheel_ixy}" iyz = "0" izz = "${wheel_iz}" />
</inertial>
</xacro:macro>

<xacro:include filename="$(find mobile_robot)/model/rover.gazebo"/>

<material name = "dark_grey">
    <color rgba = "0.2 0.2 0.2 1"/>
</material>

<material name = "silver">
    <color rgba = "0.8 0.8 0.8 1"/>
</material>

<material name = "teal">
    <color rgba = "0 0.6 0.6 1"/>
</material>

<material name = "navy">
    <color rgba = "0 0 0.4 1"/>
</material>

<material name = "burgundy">
    <color rgba = "0.6 0 0.1 1"/>
</material>

<link name = "root"/>

<joint name = "root_joint" type = "fixed">
<parent link = "root"/>
<child link = "chassis"/>
</joint>

<link name = "chassis">
    <visual>
        <geometry>
            <box size = "${chassis_length} ${chassis_width} ${chassis_height}"/>
        </geometry>
        <origin xyz = "0 0 0.15" rpy = "0 0 0"/>
        <material name = "dark_grey"/>
    </visual>

    <collision>
        <geometry>
            <box size = "${chassis_length} ${chassis_width} ${chassis_height}"/>
        </geometry>
        <origin xyz = "0 0 0.15" rpy = "0 0 0"/>
    </collision>

    <inertial>
        <origin xyz = "0 0 0.15" rpy = "0 0 0"/>
        <mass value= "${chassis_mass}"/>
        <inertia ixx = "${(1/12)*chassis_mass*(chassis_width*chassis_width+chassis_height*chassis_height)}" 
        ixy = "0" ixz = "0" 
        iyy = "${(1/12)*chassis_mass*(chassis_length*chassis_length+chassis_height*chassis_height)}" 
        izz = "${(1/12)*chassis_mass*(chassis_width*chassis_width+chassis_length*chassis_length)}" 
        iyz = "0"/>
    </inertial>
</link>

<joint name = "front_left_wheel_joint" type = "continuous">
    <parent link = "chassis"/>
    <child link = "front_left_wheel"/>
    <origin xyz = "0.25 ${-chassis_width/2-wheel_width/2} ${wheel_offset}" rpy = "0 0 0" />
    <axis xyz ="1 0 0"/>
    <limit effort = "1000" velocity = "1000"/>
    <dynamics damping = "0.8" friction = "0.8"/>
</joint>

<link name = "front_left_wheel">
    <visual>
        <geometry>
            <cylinder radius = "${wheel_radius}" length = "${wheel_width}"/>
        </geometry>
        <origin xyz = "0 0 0" rpy = "0 1.570795 0"/>
        <material name = "silver"/>
    </visual>

    <collision>
        <geometry>
            <cylinder radius = "${wheel_radius}" length = "${wheel_width}"/>
        </geometry>
        <origin xyz = "0 0 0" rpy = "0 1.570795 0"/>
    </collision>
    
    <xacro:wheel_inertia/>
</link>

<joint name = "front_right_wheel_joint" type = "continuous">
    <parent link = "chassis"/>
    <child link = "front_right_wheel"/>
    <origin xyz = "-0.25 ${-chassis_width/2-wheel_width/2} ${wheel_offset}" rpy = "0 0 0" />
    <axis xyz ="1 0 0"/>
    <limit effort = "1000" velocity = "1000"/>
    <dynamics damping = "0.8" friction = "0.8"/>
</joint>

<link name = "front_right_wheel">
    <visual>
        <geometry>
            <cylinder radius = "${wheel_radius}" length = "${wheel_width}"/>
        </geometry>
        <origin xyz = "0 0 0" rpy = "0 1.570795 0"/>
        <material name = "silver"/>
    </visual>

    <collision>
        <geometry>
            <cylinder radius = "${wheel_radius}" length = "${wheel_width}"/>
        </geometry>
        <origin xyz = "0 0 0" rpy = "0 1.570795 0"/>
    </collision>
    
    <xacro:wheel_inertia/>
</link>

<joint name = "rear_left_wheel_joint" type = "continuous">
    <parent link = "chassis"/>
    <child link = "rear_left_wheel"/>
    <origin xyz = "0.25 ${chassis_width/2+wheel_width/2} ${wheel_offset}" rpy = "0 0 0" />
    <axis xyz ="1 0 0"/>
    <limit effort = "1000" velocity = "1000"/>
    <dynamics damping = "0.8" friction = "0.8"/>
</joint>

<link name = "rear_left_wheel">
    <visual>
        <geometry>
            <cylinder radius = "${wheel_radius}" length = "${wheel_width}"/>
        </geometry>
        <origin xyz = "0 0 0" rpy = "0 1.570795 0"/>
        <material name = "silver"/>
    </visual>

    <collision>
        <geometry>
            <cylinder radius = "${wheel_radius}" length = "${wheel_width}"/>
        </geometry>
        <origin xyz = "0 0 0" rpy = "0 1.570795 0"/>
    </collision>
    
    <xacro:wheel_inertia/>
</link>

<joint name = "rear_right_wheel_joint" type = "continuous">
    <parent link = "chassis"/>
    <child link = "rear_right_wheel"/>
    <origin xyz = "-0.25 ${chassis_width/2+wheel_width/2} ${wheel_offset}" rpy = "0 0 0" />
    <axis xyz ="1 0 0"/>
    <limit effort = "1000" velocity = "1000"/>
    <dynamics damping = "0.8" friction = "0.8"/>
</joint>

<link name = "rear_right_wheel">
    <visual>
        <geometry>
            <cylinder radius = "${wheel_radius}" length = "${wheel_width}"/>
        </geometry>
        <origin xyz = "0 0 0" rpy = "0 1.570795 0"/>
        <material name = "silver"/>
    </visual>

    <collision>
        <geometry>
            <cylinder radius = "${wheel_radius}" length = "${wheel_width}"/>
        </geometry>
        <origin xyz = "0 0 0" rpy = "0 1.570795 0"/>
    </collision>
    
    <xacro:wheel_inertia/>
</link>

<!-- Sensors -->
<joint name = "lidar_mount_joint" type = "fixed">
    <parent link = "chassis"/>
    <child link = "lidar_mount"/>
    <origin xyz = "0 0.35 0.3" rpy = "0 0 0" />
</joint>

<link name="lidar_mount">
    <visual>
        <geometry>
            <cylinder radius="0.04" length="0.08"/>
        </geometry>
        <material name="teal"/>
    </visual>
    <collision>
        <geometry>
            <cylinder radius="0.04" length="0.08"/>
        </geometry>
    </collision>
    <inertial>
        <mass value="0.4"/>
        <inertia ixx="0.008" ixy="0" ixz="0" iyy="0.008" iyz="0" izz="0.008"/>
    </inertial>
</link>

<joint name = "imu_mount_joint" type = "fixed">
    <parent link = "chassis"/>
    <child link = "imu_mount"/>
    <origin xyz = "0 -0.35 0.3" rpy = "0 0 0" />
</joint>

<link name="imu_mount">
    <visual>
        <geometry>
            <cylinder radius="0.04" length="0.03"/>
        </geometry>
        <material name="navy"/>
    </visual>
    <collision>
        <geometry>
            <cylinder radius="0.04" length="0.03"/>
        </geometry>
    </collision>
    <inertial>
        <mass value="0.2"/>
        <inertia ixx="0.005" ixy="0" ixz="0" iyy="0.005" iyz="0" izz="0.005"/>
    </inertial>
</link>

<joint name = "gps_mount_joint" type = "fixed">
    <parent link = "chassis"/>
    <child link = "gps_mount"/>
    <origin xyz = "-0.15 0 0.3" rpy = "0 0 0" />
</joint>

<link name="gps_mount">
    <visual>
        <geometry>
            <cylinder radius="0.04" length="0.03"/>
        </geometry>
        <material name="burgundy"/>
    </visual>
    <collision>
        <geometry>
            <cylinder radius="0.04" length="0.03"/>
        </geometry>
    </collision>
    <inertial>
        <mass value="0.2"/>
        <inertia ixx="0.005" ixy="0" ixz="0" iyy="0.005" iyz="0" izz="0.005"/>
    </inertial>
</link>

<joint name = "camera_mount_joint" type = "fixed">
    <parent link = "chassis"/>
    <child link = "camera_mount"/>
    <origin xyz = "0.15 0 0.3" rpy = "0 0 0" />
</joint>

<link name="camera_mount">
    <visual>
        <geometry>
            <box size="0.04 0.04 0.04"/>
        </geometry>
        <material name="silver"/>
    </visual>
    <collision>
        <geometry>
            <box size="0.04 0.04 0.04"/>
        </geometry>
    </collision>
    <inertial>
        <mass value="0.2"/>
        <inertia ixx="0.005" ixy="0" ixz="0" iyy="0.005" iyz="0" izz="0.005"/>
    </inertial>
</link>

<joint name = "stereo_mount_joint" type = "fixed">
    <parent link = "chassis"/>
    <child link = "stereo_mount"/>
    <origin xyz = "0.15 0.15 0.3" rpy = "0 0 0" />
</joint>

<link name="stereo_mount">
    <visual>
        <geometry>
            <box size="0.04 0.04 0.04"/>
        </geometry>
        <material name="silver"/>
    </visual>
    <collision>
        <geometry>
            <box size="0.04 0.04 0.04"/>
        </geometry>
    </collision>
    <inertial>
        <mass value="0.2"/>
        <inertia ixx="0.005" ixy="0" ixz="0" iyy="0.005" iyz="0" izz="0.005"/>
    </inertial>
</link>

</robot>
